### ISSUE TITLE
enable license checks in spotless to be more flexible/configurable

### ISSUE THREAD

**Issue by rbarkerSL** [hiero-ledger/hiero-gradle-conventions#48]
Should be able to configure whether spotless uses the SPDX convention for license checks or not.

**Comment by jjohannes** [comment]
We should first clarify if this is really needed. I think on the long run, all repos will use the short and simple _SPDX convention header_.

But if we need it, I would suggest to implement it like this:

- Optionally, a repository can contain a file `gralde/license-header.txt`. If (and only if) that files exists, the content of the files is taken as header. Otherwise, we default to what we have now.

cc @hendrikebbers

**Comment by jsync-swirlds** [comment]
There may be cases where an organization wants to use this plugin for consistency across both Heiro contributions and internal codebases that may, or may not, eventually be contributed to Heiro.
Allowing for internal headers that are not SPDX (because those internal codebases are not "open" licensed) as an option makes it easier for those organizations to contribute.

The proposed mechanism appears, to me, to be a good way to enable that flexibility.
